name: main
on: 
  push:
    paths-ignore:
    - docs
    - script/src/answers.js
    - script/src/problems.js
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: setup-nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: setup-python3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: main
        env:
          ACCESS_TOKEN:  ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.email "h.nakamura0903@gmail.com"
          git config --global user.name "nekoTheShadow"
          git clone https://github.com/nekoTheShadow/codeforces.git
          cd ${GITHUB_WORKSPACE}/codeforces/script
          python3 script/answers.py
          python3 script/problems.py
          yarn install
          yarn build
          git add -A
          git commit -m "CI From Github Actions $(date '+%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${ACCESS_TOKEN}@github.com/nekoTheShadow/codeforces.git master


